package com.aionemu.gameserver.ai2.poll;

/**
 * @author ATracer
 */
public enum AIQuestion {

	DESTINATION_REACHED,
	CAN_SPAWN_ON_DAYTIME_CHANGE,
	SHOULD_DECAY,
	SHOULD_LOOT,
	SHOULD_RESPAWN,
	SHOULD_REWARD,
	SHOULD_REWARD_AP,
	CAN_RESIST_ABNORMAL,
	CAN_ATTACK_PLAYER,
	CAN_SHOUT
}
