<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../items/item_templates.xsd" />
	<xs:element name="decomposable_items">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="decomposable" type="DecomposableItem" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="DecomposableItem">
		<xs:sequence>
			<xs:element name="set" type="DecomposableSet" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="item_id" type="itemId" use="required" />
		<xs:attribute name="selectable" type="xs:boolean" default="false" />
		<xs:attribute name="only_one" type="xs:boolean" default="false" />
	</xs:complexType>
	<xs:complexType name="DecomposableSet">
		<xs:sequence>
			<xs:element name="item" type="DecomposedItem" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="chance" type="xs:float" default="100" />
		<xs:attribute name="min_level" type="xs:int" default="1" />
		<xs:attribute name="max_level" type="xs:int" default="80" />
		<xs:attribute name="race" type="Race" default="PC_ALL" />
		<xs:attribute name="player_classes" type="ListPlayerClass" />
	</xs:complexType>
	<xs:complexType name="DecomposedItem">
		<xs:attribute name="id" type="itemId" use="required" />
		<xs:attribute name="count" type="xs:int" default="1" />
		<xs:attribute name="chance" type="xs:float" default="100" />
	</xs:complexType>
	<xs:simpleType name="ListPlayerClass">
		<xs:list itemType="playerClass" />
	</xs:simpleType>
</xs:schema>
