ALTER TABLE abyss_rank ADD COLUMN daily_gp INT(11) NOT NULL DEFAULT 0;
ALTER TABLE abyss_rank ADD COLUMN weekly_gp INT(11) NOT NULL DEFAULT 0;
ALTER TABLE abyss_rank ADD COLUMN gp INT(11) NOT NULL DEFAULT 0;
ALTER TABLE abyss_rank ADD COLUMN last_gp INT(11) NOT NULL DEFAULT 0;