package com.aionemu.gameserver.model.templates.item;

import javax.xml.bind.annotation.XmlEnum;

/**
 * @author vlog
 */
@XmlEnum
public enum RandomType {

	ENCHANTMENT,
	MANASTONE,
	MANASTONE_COMMON_GRADE_10(10),
	MANASTONE_COMMON_GRADE_20(20),
	MANASTONE_COMMON_GRADE_30(30),
	MANASTONE_COMMON_GRADE_40(40),
	MANASTONE_COMMON_GRADE_50(50),
	MANASTONE_COMMON_GRADE_60(60),
	MANASTONE_COMMON_GRADE_70(70),
	MANASTONE_RARE_GRADE_10(10),
	MANASTONE_RARE_GRADE_20(20),
	MANASTONE_RARE_GRADE_30(30),
	MANASTONE_RARE_GRADE_40(40),
	MANASTONE_RARE_GRADE_50(50),
	MANASTONE_RARE_GRADE_60(60),
	MANASTONE_RARE_GRADE_70(70),
	MANASTONE_LEGEND_GRADE_10(10),
	MANASTONE_LEGEND_GRADE_20(20),
	MANASTONE_LEGEND_GRADE_30(30),
	MANASTONE_LEGEND_GRADE_40(40),
	MANASTONE_LEGEND_GRADE_50(50),
	MANASTONE_LEGEND_GRADE_60(60),
	MANASTONE_LEGEND_GRADE_70(70),
	SPECIAL_MANASTONE_RARE_GRADE(70),
	SPECIAL_MANASTONE_LEGEND_GRADE(70),
	SPECIAL_MANASTONE_UNIQUE_GRADE(70),
	SPECIAL_MANASTONE_EPIC_GRADE(70),
	ANCIENTITEMS,
	ANCIENT_CROWN,
	ANCIENT_GOBLET,
	ANCIENT_SEAL,
	ANCIENT_ICON,
	CHUNK_EARTH,
	CHUNK_ROCK,
	CHUNK_SAND,
	CHUNK_GEMSTONE,
	SCROLLS,
	POTION,
	LESSER_POTIONS,
	POTION_50,
	ILLUSION_GODSTONE,
	PREMIUM_OPHIDAN_RECIPE;

	private int level;

	private RandomType() {
	}

	private RandomType(int level) {
		this.level = level;
	}

	public int getLevel() {
		return level;
	}
}
