package com.aionemu.gameserver.ai.poll;

/**
 * @author ATracer
 */
public enum AIQuestion {

	DESTINATION_REACHED,
	SHOULD_DECAY,
	SHOULD_LOOT,
	SHOULD_RESPAWN,
	SHOULD_REWARD,
	SHOULD_REWARD_AP,
	CAN_RESIST_ABNORMAL,
	CAN_ATTACK_PLAYER,
	CAN_SHOUT,
	SHOULD_CAN_SEE_ADD_BOUNDS_ON_ATTACK,
	SHOULD_CAN_SEE_ADD_BOUNDS_ON_ATTACKED
}
