package com.aionemu.gameserver.ai.poll;

/**
 * @author ATracer
 */
public enum AIQuestion {

	DESTINATION_REACHED,
	DECAY,
	LOOT,
	RESPAWN,
	REWARD,
	REWARD_AP,
	RESIST_ABNORMAL,
	ATTACK_PLAYER,
	SHOUT,
		ADD_BOUNDS_ON_ATTACK,
		ADD_BOUNDS_ON_ATTACKED,
	REMOVE_EFFECTS_ON_MAPREGION_DEACTIVATE
}
