package com.aionemu.gameserver.world;

/**
 * @author Aioncool, Bobobear
 */
public enum WorldDropType {
	ASMODAE,
	ELYSEA,
	ABYSS,
	ABYSS_INSTANCE,
	PANESTERRA,
	ARENA_INSTANCE,
	BALAUREA,
	BALAUREA_INSTANCE,
	TIAMARANTA_SARPAN,
	SARPAN_INSTANCE,
	TIAMARANTA_INSTANCE,
	KATALAM,
	IDIAN_DEPTH,
	KATALAM_INSTANCE,
	DREDGION_INSTANCE,
	BATTLEFIELD_INSTANCE,
	STEEL_ROSE_INSTANCE,
	STEEL_RAKE_INSTANCE,
	OTHER_INSTANCES,
	NONE
}
