#
# ----------------------------
# Geodata config's:
# ----------------------------

# Geo data mode:
# - OFF: Skips loading of geo data entirely, so obstacle detection, terrain checks and environment effects, such as lava damage, fortress shields or
#   EoR recovery zones will not work. Use for testing or in memory constrained environments.
# - MATERIALS_ONLY: Skips loading of most geo data, so obstacle detection, terrain checks and terrain-based effects, such as lava damage, will not
#   work. Geometries that trigger skills are loaded (shields, EoR regenerating zones, etc.). Use for testing or in memory constrained environments.
# - ON: All geo data is loaded and validated.
# Default: ON
gameserver.geodata.mode = ON

# Enable canSee checks using geodata.
# Default: true
gameserver.geodata.cansee.enable = true

# Enable fear skill using geodata.
# Default: true
gameserver.geodata.fear.enable = true

# If enabled - during movements npcs will be checking z coordinate based on geo if target is flying
# Default: true
gameserver.geodata.npc.move = true

# Show collision zone name and skill id for GMs
# Default: false
gameserver.geodata.materials.showdetails = false
