name: Deploy

on:
  workflow_dispatch:
    inputs:
      server:
        type: choice
        description: Server to build
        options:
          - chat-server
          - game-server
          - login-server
        default: game-server
      skip-tests:
        type: boolean
        description: Skip tests during build

jobs:
  build:
    name: Deploy ${{ github.event.inputs.server }}
    runs-on: ubuntu-latest
    environment: 'production'
    concurrency: ${{ github.event.inputs.server }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B -Dmaven.source.skip=true -Dmaven.test.skip=${{ github.event.inputs.skip-tests }} -pl :${{ github.event.inputs.server }} -am package
      - name: Deploy
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ github.event.inputs.server }}/target/*.zip
          target: .
          strip_components: 2
